### ISSUE TITLE
SetPower Pt35 fridge/freezer test notes

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ElectricRCAircraftGuy/eRCaGuy_product_data#1]
5:15pm: I set the left side to 16 deg F instead of 0 deg F in an attempt to give the right side more cooling time since it appears to be sharing cooling time right now 50/50 between the two sides.

Now the left is set to 16 F and right is set to 0 F.
Previously both were set to 0 F.

Actual Temps were last about 7 F left and about 28 F right. As you can see, the right side is way too warm so I'm trying to give the right side more cooling time.

**Comment by ElectricRCAircraftGuy** [comment]
7:38pm. See photos. 

Left is set to 16 F and it is 21 F on the display and 21.4 F on the YoLink.
Right is set to 0 F and it is 12 F on the display and 14.4 F on the YoLink.

Nice! My theory is working! And the display temp is more accurate!

Changing set points as follows:
L 10F.
R 10F.

Let's see what happens now!

**Comment by ElectricRCAircraftGuy** [comment]
9/1/24  
6:41am  

L display reads 10F. YoLink is 19.8F.  
R display reads 16F. YoLink is 10.8F.

Seconds later while writing this:  
L display reads 19F. YoLink is 20.7F.
Right display reads 13F. YoLink is 10.6F. 

The display temp is all over the place! Might be because the temp sensor is inside a thermal tube or something and the cooling was active on the R over that time.

Outside temp is 90F. Cooler is in the shade inside the Tesla in the garage.

---

6:48am: raising both set points from 10F to 14F.

---

Test setup:  
![Screenshot_20240901-065740](https://github.com/user-attachments/assets/9c76f3ad-b60f-48fc-b3fa-0b334c6c51a4)

Temp sensor 4 is the air outside the cooler, in the Tesla.  
Temp sensor 6 is in the L compartment in a plastic bowl, and 7 in the R in a plastic bowl.  2 is also in the R but on the floor of the R.

**Comment by ElectricRCAircraftGuy** [comment]
The displays are off by as much as +/- 10F. So if a display reads 30F, it might actually be 20F or 40F inside the compartment. 

The accuracy of the displays is **significantly worse** if neither set point can ever be reached. So, if both sides are on, have an average set point (averaged between the two sides) of perhaps 16F or more to allow the set points to be reached to improve the temperature accuracy of the displays. This is assuming cooling power is set to max.

Ultimately, the pump is too small and a more powerful compressor pump needs to be added to this unit to allow it to perform better.

**Comment by ElectricRCAircraftGuy** [comment]
8:31am

Left side is at 25.3F on the YoLink and 24 F on the display. 

Raising both set points to 16F to try to help it go down.

**Comment by ElectricRCAircraftGuy** [comment]
9/1/24
12:41pm

YoLink: 30.2F, 17.8F
Display: 23F, 19F

Changing both set points to 19F now to try to get the L temp down.

**Comment by ElectricRCAircraftGuy** [comment]
2:12pm: I unplugged the freezer and plugged it back in to try to reset it to make it hopefully work properly and share the load equally. I wonder if an integral error windup has occurred from the 2 days where the right compartment was too warm, causing it to spend too much time cooling the right side now, letting the left get too warm. 

So, I unplugged it and plugged it back in, intentionally resetting my power meter too.

The set point for each side is still set to 19F.

**Comment by ElectricRCAircraftGuy** [comment]
3pm:

YoLink: 33.6F, 19.0F
Display: 24F, 19F

Changed L set point to 10F to drop the temp since it's off by so much.

Set points: 10F (just lowered), 19F (same as previously)

**Comment by ElectricRCAircraftGuy** [comment]
5:17pm:

YoLink: 22.6F, 21.7F  
Display: 15F, 22F  
Setpoints: 10F, 19F  

New setpoints I'm setting now: 16F, 23F.  
Goal is 23F in both compartments!--which takes ~50W continuous with an ambient temp of 91F.

**Comment by ElectricRCAircraftGuy** [comment]
7:32pm

```
YoLink: 22.1F, 26.8F
Display: 16F, 25F
Setpoints: 16F, 23F

New setpoints: 18F, 19F
```

Goal is to get 23F in each side.

**Comment by ElectricRCAircraftGuy** [comment]
9:46pm

```
YoLink: 25.5F, 18.9F, 82.8F in Tesla
Display: 19F, 19F
Setpoints: 18F, 19F

New setpoints: 16F, 23F
```
Goal is 23F per side.

**Comment by ElectricRCAircraftGuy** [comment]
11:37pm

New setpoints: 18F, 21F (19.5 F avg).

I think goal of 23F per side is too low for this power level of compressor. **New goal is 25F per side (peaks of 26-27F max).** Making your avg set point 20F may do that.

**Comment by ElectricRCAircraftGuy** [comment]
2 Sept 2024.  
1139am

```
YoLink: 23.0F, 25.0F, 94.6F in Tesla
Display: 19F, 21F
Setpoints: 18F, 21F

New setpoints: 19F, 19F
```
Goal is 25F per compartment side (peaks of 27F max). Using an avg. setpoint of 19F between the two sides may do that.

Power draw is 54W.

**Comment by ElectricRCAircraftGuy** [comment]
2:13pm

```
YoLink: 29.7F, 20.7F, 92.5F in Tesla
Display: 22F, 25F
Setpoints: 19F, 19F

New setpoints: 18F, 19F.
```

Trying to lower the temp on the left since it's 10 deg higher than setpoint.

Power draw is 48W.

#### Potential rule of thumb: 

Don't make both sides have the same setpoint. It never seems to work. Always make them off by at least 1 deg F. Ex: 18F L and 19F R.

#### Goal: 
20-25F per side, with peaks of 27.5F or less.

#### notes

Display thermometer is inside the cooling walls somewhere, so it changes rapidly, long before the air changes, and can be up to 10 deg F lower than the air temp when cooling.

For freezing, setpoint should be 14 deg F lower than the desired temp, and not lower than 18F or so if both sides are set to freezer. Ex: set L to 18 F and R to 19 F to get both to 20-25 F indefinitely.

**Comment by ElectricRCAircraftGuy** [comment]
1031pm

```
YoLink: 25.7F, 20.5F, 91.6F in Tesla
Display: 18F, 23F
Setpoints: 18F, 19F

New setpoints: 18F, 21F
```
Raised the right temp to try to allow the left side more cooling time.

Note : cannot set to 20F due to internal usage of Celsius, not Fahrenheit. 19F up one is 21F on the setpoint.

**Comment by ElectricRCAircraftGuy** [comment]
3 Sept 2024.  
2:29pm
 
```
YoLink: 38.5F, 28.0F, 115.5F in Tesla
Display: 29F, 22F
Setpoints: 18F, 21F

New setpoints: 16F, 21F
```

60W power draw.

Trying to reduce temp in left compartment. 

Ice is melting in L compartment a little bit inside the bottle. R side bottle is still solid. Both sides have a few liquid drops from melt of condensation ice inside the cooler.

**Comment by ElectricRCAircraftGuy** [comment]
431pm

```
YoLink: 30.2, 29.7, 102.9 in Tesla
Display: 21 (was 18 just seconds ago), 27
Setpoints: 16, 21
```

**Comment by ElectricRCAircraftGuy** [comment]
437pm

```
YoLink: 30.6, 27.5, 99.3
Display: 22 (was 25 seconds ago), 24
```

**Comment by ElectricRCAircraftGuy** [comment]
Tesla was outside in the sun all day today with Sentry Mode on to keep the outlets on, and I'll leave it outside all night tonight in Sentry Mode too.

Charge was 70% this morning at 530am. It's 59% now at 440pm.

I calculate the cooler to take 2% or less per 24 hours, so the rest of the usage is Sentry Mode.

**Comment by ElectricRCAircraftGuy** [comment]
The sun shining on the cooler seems to make a big difference. Cover it with a window shade during the day, especially if you leave it in the smoking hot car all day.

Notice the peak here. I think it's due to being in direct sunlight (inside the back of the Tesla Model Y).

![Screenshot_20240903-171529](https://github.com/user-attachments/assets/20d3d145-718c-4883-815c-de886a3fca22)

**Comment by ElectricRCAircraftGuy** [comment]
# Plan/test cases

Do temp setpoint changes every 24 hours at 6pm~9pm.

1. [x] Let it run for another 24 hours as-is--no changes. 
2. [x] Then, let it run 24 hours set to 10F L and 30F R and see what happens. 
3. [x] Then, set it to 0F 0F again and let it run a final 24 hours. Keep the ice chest in the back of my car, car outside the garage, the whole time, so it gets the cool of the night and the heat of the sun.
4. [x] Then, try new temps based on what you learn from 2 above. Ex: 20F L and 40F R, perhaps. Again, 24 hours, switching it up each night around 6pm.
5. [x] Turn off the R compartment and try L at 0F.
6. [x] Turn off the L compartment and try R at 0F.

**Comment by ElectricRCAircraftGuy** [comment]
Email from SetPower on how to reset the temperature calibration values for the display readings: https://mail.google.com/mail/u/0/#inbox/FMfcgzQVzXRwCsVJnpGppZhqVKVmzQSL

---------- Forwarded message ---------
From: SP-support <support@setpowerusa.com>
Date: Mon, Sep 2, 2024 at 3:01 AM
Subject: 113-4582998-4301847-PT35

> Hi there,
> Thank you for reaching out to us, we apologize for any inconvenience caused. 
> 
> Because of the sinking nature of cold air, the different temperatures may exist in different locations in the refrigerator (the temperature of the bottom will be the lowest). The panel only shows the average temperature of the whole refrigerator.
> If the temperature difference exceeds 7℉, please check if the temperature compensation values for the right zone are set to their default factory values. To do this, follow these steps:
> --Adjust the temperature unit display to Celsius (℃). 
> Under power-on condition, long press (COMPRESSOR SPEED) “SET”, (RIGHT BIN) “UP” and (RIGHT BIN) “DOWN” for 3 seconds, then press (COMPRESSOR SPEED) “SET” to enter the temperature compensation setting menu of the right box (the same as the left box), then short press (COMPRESSOR SPEED) “SET” to cycle through the right box (the same as the left box). “ key for 3 seconds to enter the right box (left box, the same) temperature compensation settings menu, followed by a short press (COMPRESSOR SPEED) area “SET” key can cycle through the selection of F1/F2/F3 three compensation segments (digital tube flashes accordingly to display F1, F2, F3). After selecting the compensation section to be set, short press the (RIGHT BIN) area “UP” or (RIGHT BIN) area “DOWN” key to set the compensation value of the section.

**Comment by ElectricRCAircraftGuy** [comment]
## 1. Let it run for another 24 hours as-is--no changes. 

Ending at 8:15pm

```
YoLink: 24.4, 23.5, 87.8 in Tesla
Display: 19, 21
Setpoints: 16, 21
```

Tesla battery: 52%

Results: (insert plots/screenshots from phone)

**Comment by ElectricRCAircraftGuy** [comment]
## 2.  Then, let it run 24 hours set to 10F L and 30F R and see what happens.

Adding room temp water to each compartment:

2636g L, 1046g R

8:21pm
```
YoLink: 24.4, 24.6, 86.0 in Tesla
Display: 16, 24
New setpoints: 5, 34 (avg: 19.5F)
```
I took the previous quart-sized Gatorade ice bottles out. They are both frozen solid.

**Comment by ElectricRCAircraftGuy** [comment]
9:30pm

```
YoLink: 29.5, 38.1, 82.4
Display: 22, 37
New Setpoints: 5, 32 (avg: 18.5F)
```

**Comment by ElectricRCAircraftGuy** [comment]
5:55am

```
YoLink: 12.0, 33.4, 70.2
Display: 10, 31
New Setpoints: 10, 32 (avg: 21.0)
```
Left compartment is rarely hitting its setpoint (looking at the humidity plot you can see it occasionally is), so I need to raise it. Right compartment has a touch of frost, but no ice in the water bottle, so it's fine. I'm sure it will rise a bit in the day's heat too.

Water bottle in the L is about 1/3 of the way frozen through. It has an interior shell of ice, with water in the center. This may be inhibiting the reducing of the temperature in that side too since the liquid water will absorb so much energy as it freezes.

Raising the L to 10F helped it hit its setpoint. Neither side is cooling right now, and the compressor is off, and the unit's power draw is a measly 0.7W.

Didn't last long. Compressor is now on on the left. Let's let the left water bottle freeze solid, then see how it performs. If it still never hits its setpoint consistently throughout the day with solid ice inside it, then I may need to raise the L setpoint to 15F, possibly giving this test a whole nother day to perform.

It didn't stay on long either. Good. The compressor is off again, with neither side on. Good, this means it is cycling now. The goal is to get to setpoints that allow the compressor to cycle on and off to give it a break. We don't want the compressor on continually all the time -- only while first cooling to initially reach the setpoints. But the setpoints must be *possible* to reach. 

Tesla is at 49% charge.

**Comment by ElectricRCAircraftGuy** [comment]
7:35am: looking at the humidity plot, the compressor is clearly cycling in the L compartment now, which is good. The temperature may be rising in part because there is still a bottle of partially liquid water inside, and liquid water can't get less than 32F no matter what, until it all freezes first.

6 is L. 7 is R.

![Screenshot_20240905-073511](https://github.com/user-attachments/assets/a9561d6a-af07-4fdb-9fcd-c8e20bf2deba)

![Screenshot_20240905-073525](https://github.com/user-attachments/assets/58e7e5d6-7abe-4932-991c-b9c58e5cab30)

**Comment by ElectricRCAircraftGuy** [comment]
8:42am

```
YoLink: 20.8, 34.0, 92.7
Display: 10, 32
Setpoints: 10, 32
```

Opening both compartments. 

Water bottle on L is still mostly water. **Just added my 2x 1 quart water bottles with room temperature water to the R.** No frost on R anymore. Just a hazy film that instantly becomes water if you touch it.

**Comment by ElectricRCAircraftGuy** [comment]
9:58am

```
YoLink: 25.7, 43.7, 105.8
Display: 11, 41
Setpoints: unchanged
```

**Comment by ElectricRCAircraftGuy** [comment]
Note that my car gets the morning sun, and is shaded in the afternoon, when outside. The back of my car faces East, and the car is parked on the East side of the house, and the SetPower fridge/freezer is in the back of my car, so sun can shine onto it and heat it directly through my tinted Tesla Model Y hatchback glass.

**Comment by ElectricRCAircraftGuy** [comment]
3:04pm

```
YoLink: 34.3, 41.0, 124.3. 
Display: 18, 39
Setpoints: still 10, 32
```
The car just got in the shade from the house. Insolation and radiative heating is now gone, hence the significantly improved cooling in both chambers.

Water bottle in L compartment still has ice but is melted more. In R compartment the water is nice and cold when I drink it.

**Comment by ElectricRCAircraftGuy** [comment]
In observing, the actual temp in L can be as much as **17 deg F** hotter than the display temp. In the R it is much better, perhaps **6 deg F.** I think this is because the L chamber is over the hot pump and heat exchanger. This is exacerbated dramatically when the cooler is in direct sunlight, especially when inside a closed, hot car.

I assert that though the unit is good, **the pump/compressor is undersized and really should be bigger for a unit of this size** in order to **maintain cold temps in the summer, and in order to get < 10-12 F in general.**

**Comment by ElectricRCAircraftGuy** [comment]
## Solar recommendations 

1. Take the unit out of the car if the sunlight is hitting the car and the car is off. 
2. If you can't do that, use sunshades over your front and rear car windows.
3. If the unit is outside in the sunlight, put a sunshade over it.
4. If you keep the sun from shining on your unit, it can keep refrigeration temps (< 42 deg) in temps up to 130 F, and freezer temps (< 32 F) in temps up to 100+ F.

Getting < 10 F is virtually impossible in either compartment no matter what you do.

**Comment by ElectricRCAircraftGuy** [comment]
## Tesla battery usage

2% per day in power usage + another 10% per day to keep my car in Sentry Mode mode where it keeps the 12V outlet power on. So 12% per day, with most of that being Teslas fault. You could run it on a portable battery pack.

**Comment by ElectricRCAircraftGuy** [comment]
## Portable battery pack

The unit draws ~52W continuous when on. Let's give some buffer: 52W/.8 = 65W. So, to run it for 4 days we would need a battery pack that is at least 65W * 4 days * 24 hours/day = **6240 Whr** / 12V = **520 Ahr.** Let's see what Amazon has.  

If you run the unit in colder weather or with higher setpoints, however, it won't be on all the time. Instead, it will cycle on and off and have periods of time with nearly 0W power usage, resting, in which case it will last much longer or require much less energy for a given amount of time. 

1. $1300, 2048 Wh: https://amzn.to/3XbvlT7 - would last 2048Whr / 65W = 31.5 hours.
    $1300 / 31.5 hours = $41.27/hour
1. $700 Ecoflow 1612 Wh: https://amzn.to/3X7p0YA - would last 1612 Wh/65W = 24.8 hours.
    $700 / 24.8 hours = $28.23/hour  <-- **best value**
1. $120 after coupon: 257Wh: https://amzn.to/3TjfYH1 - would last 257Whr / 65W = 3.95 hours. 
    $120 / 3.95 hours = $30.38/hour
1. $500 1024 Whr: https://amzn.to/3zjga25 - would last 1024 Whr/65W = 15.7 hours
    $500 / 15.7 hours = $31.85/hour
1. $500 48V 20Ah --> 48x20 = 960 Whr: https://wildewayebike.com/products/upgrade-20ah-lithium-battery-for-new-version-x7 - plug the 120V to 12V AC adapter that comes with the SetPower straight into this 48V battery to regulate down to 12V - would last 960 Wh / 65W = 14.8 hours.
    $500 / 14.8 hours = $33.78/hour
1. Jackery
    1. 1070 Wh, $500 - https://www.amazon.com/Jackery-Explorer-Portable-Generator-Emergency/dp/B0D7PPG25F - would last 1070 Wh / 65W = 16.5 hours.
        $500 / 16.5 hours = $30.30/hour
    1. 2042 Wh, $1600 - https://www.amazon.com/Jackery-Generator-Expandable-Compatible-Emergency/dp/B0C6DHK68Q

You could also just charge it from your 12V cigarette lighter in your car while driving, and from a generator when camping/stopped, instead. 

### TODO:
1. [ ] Also look into Alibaba and Aliexpress products like this: https://www.alibaba.com/product-detail/2024-New-Hot-Selling-Luxury-5376Wh_1601141741576.html


## Best generator:
1. $1100: [Champion Power Equipment 6500-Watt RV Ready Portable Inverter Generator with Quiet Technology and CO Shield](https://amzn.to/4dTQKY0) - can charge my **Tesla Model Y** from 0% to full (100%) in (80000 Whr / (240V x 20.8A) = **16.0 hours**, in theory. In actuality it would be a couple hours longer due to the nature of constant Voltage --> decreased current as the SoC reaches 100%.

**Comment by ElectricRCAircraftGuy** [comment]
8:24pm

```
YoLink: 23.5, 37.6, 90.0
Display: 16 (then 25), 34--after a few minutes of the L side being ON (cooling), it then showed 25.
Setpoints: 10, 32
New Setpoints: 7, 32 (avg 19.5F)
Update: 7, 34 I think (avg: 20.5)
```

Opening compartments to look. L water bottle is still very watery. Water drops in bottom of compartment are frozen now. R is nice and cold. Ice/Frost is formed around the top of the compartment on the walls. 

**I ate dinner in front of the cooler and stared at it for about 30 minutes.** Over the course of about 15 minutes, the left display, as the L side cooled, went from 25F to 7F. It was faster once it got started. The right side stayed at 36F the whole time. Then it spent about 1.5 minutes off, not cooling, then it went to the R side for a while --maybe 12 minutes, then back to L again. The R side display didn't change much --stayed constant actually at 36 F. The L side fluctuated from 7 to 23 and back to 7. 

My hypothesis is that the heat from the compressor and heat exchanger is seeping into the L compartment, causing massive fluctuations where the thermometer is embedded in the walls of the L compartment. The R side seems to be much more steady, much more consistent, and require much less cooling to hold its temperature once cooled.

**Comment by ElectricRCAircraftGuy** [comment]
6:21am

```
YoLink: 15.8, 35.1, 90.5
Display: 18, 36, cooling on L
Setpoints: still 7, 34
```

The 2 quart water bottle in the Left was about 65% frozen. Still had a lot of water in it. I rested it on its narrower side to freeze faster, since the bottom and top (when resting on its wider side) were still liquid. 

The R compartment had frost/frozen drops of water all along its upper edges near the few inches to the top. That must be the coldest part in that compartment. The bottom was about 34-35F. 

7F, 34F seems to be a really good setpoint to use. The freezer, incl the L side, *is* cycling even though we don't see temp fluctuations over there, as I watched the L display get from 18 to 7F in a few minutes staring at it, and briefly turn off the compressor and stop cooling both sides, before it turned it back on on the L again a few minutes later. And then it shifted to the R before the L had recooled back to 7, since the R was at 36 and needed cooling again.

**Comment by ElectricRCAircraftGuy** [comment]
6:37am

Moving car out of garage and into the sunlight.

Tesla Model Y is at 70%.

**Comment by ElectricRCAircraftGuy** [comment]
1:05pm

I just checked both compartments. L one's water bottle is 95% frozen solid. Just a touch of water still on one side. R one still has ice formed near the top even though the bottom is 38F.

**Comment by ElectricRCAircraftGuy** [comment]
## Best Setpoints: 7F, 34F

This keeps it around 15\~20F on the Left, and 34\~38F on the Right, while still letting it periodically hit both setpoints to allow the compressor pump to cycle on and off to rest.

---

Note: water bottle on left was frozen solid. Ice/frost is in both sides. On the Right it's near the top.

So it took about 2 days to go from room temp to frozen solid.

**Comment by ElectricRCAircraftGuy** [comment]
# 3. Then, set it to 0F 0F again and let it run a final 24 hours. Keep the ice chest in the back of my car, car outside the garage, the whole time, so it gets the cool of the night and the heat of the sun.

8:42pm

Changed both Setpoints to 0F.

**Comment by ElectricRCAircraftGuy** [comment]
1031pm 

Dumped out some water in the R water bottles so they won't burst when they freeze solid eventually.

Tesla is at 62% charge. Switching from Sentry mode to Camping Mode with AC off to see if that uses less energy to keep the outlets on.

Nevermind. Camping Mode CANT be on with AC off. It turns AC on. Back to Sentry Mode.

**Comment by ElectricRCAircraftGuy** [comment]
9-7-24.  
6:03am

```
YoLink: 2.8, 12.0, 71.2
Display: 10, 18
Setpoints: still 0, 0
```

The fact that the L compartment started with solid ice in its water bottle helped it a lot I think. L bottle is still solid. R 3x bottles are partially (40%?) frozen, with a solid ring if ice inside them, with water inside that. This liquid water may be / is likely what's keeping the R side from getting as cold as the L side. So, I may have to continue this experiment another 24 hours after today.

**Comment by ElectricRCAircraftGuy** [comment]
I took a short drive. Tesla at 52% now.

**Comment by ElectricRCAircraftGuy** [comment]
6:10am. Tesla at 49% now. The reading above was around 12 hours ago. 

## Note: if you put 2 quarts of 80 deg water into the cooler and set it to low freezing temps, it could take 2+ days to freeze solid in this freezer.

**Comment by ElectricRCAircraftGuy** [comment]
6:50am

2 quart water bottle in L is frozen solid and the air is -1.8F. The 3 water bottles in the R are *almost* frozen solid. There is still some liquid in them. And the air is 12.4F. So, I need to give this test another day beyond today since the liquid water is at 32F, due to the physics of state change, which is preventing the R freezer from reaching its minimum capability in temperature.

**Comment by ElectricRCAircraftGuy** [comment]
7:02pm

Tesla is at 70%. I just unplugged it and pulled it out of the garage to be in the driveway again to let it cool off.

**Comment by ElectricRCAircraftGuy** [comment]
10:20pm

R water bottles still have a *tiny* bit of liquid water in them. Not quite frozen solid yet.

**Comment by ElectricRCAircraftGuy** [comment]
5:14am: 

Tesla is at 67%

5:50am:

Water is frozen solid in R compartment now too. Both sides are close to 0F.

### One or both compartments CAN hit \~0F so long as:
1. The ambient temp is \~75F or less.
2. There is no liquid water inside the compartments. All water needs to have fully phase changed to ice, because physics dictates that liquid water be 32F as it freezes, which holds the compartment temp high until all water has changed to ice.

**Comment by ElectricRCAircraftGuy** [comment]
8:15am

I drove the car. It's parked outside again now. 63% SoC.

**Comment by ElectricRCAircraftGuy** [comment]
2:52pm

The 137.7 is in the glove box in the Tesla.
116.2 in back of Tesla by freezer. Sensors 6 and 7 are the left and right freezer compartments, respectively.

![Screenshot_20240909-145221](https://github.com/user-attachments/assets/5717a08d-6313-4bf3-9fc5-97a4c3abdc0f)

**Comment by ElectricRCAircraftGuy** [comment]
8:41pm

```
YoLink: 5.2, 26.4, 78.4
Display: 5, 28
Setpoints: 0, 0
```

See photos of plots.


# Test 4. Turn off the L compartment and try R at 0F.

8:50pm. 

Tesla is at 52% SoC.

Starting the new test! L compartment off. R compartment has all the frozen water bottles in it and is set to 0F

```
New Setpoints: NA, 0
```

**Comment by ElectricRCAircraftGuy** [comment]
5:25am

```
YoLink: 61.2, -5.1, 66.2 in Tesla
Display: off, 3
Setpoints: off, 0
```

I opened the L compartment and wiped all the water and moisture out. I opened the R compartment and looked and felt the ice. Of course it's rock hard being -5.1F.

**Comment by ElectricRCAircraftGuy** [comment]
8:22am

Tesla is at 45% after running some errands. Sitting in driveway.

11:49am: 

Tesla is at 37% after errands.

The Tesla says that sentry mode has used 14.8% SoC charge since last charge, 44 miles ago

**Comment by ElectricRCAircraftGuy** [comment]
# Test 5: L 0F, R off with ice bottles in it

9:38pm 10 Sep. 2024

```
YoLink: 79.9, -5.6, 79.0 in Tesla
Display: off, 3
Setpoints: off, 0.

New setpoints: 0, off
```

Turning on L compartment and off R one. Moving most ice bottles to L while leaving two in R.

See all photos.

**Comment by ElectricRCAircraftGuy** [comment]
5:50am

Backed the car out of the hot garage and into the cold morning air. I opened all the windows and the back trunk for several minutes to cool down the interior of the car to let the L freezer compartment get colder.

Tesla is at 70% SoC. Just unplugged it.

**Comment by ElectricRCAircraftGuy** [comment]
8:26am

Power draw is 40.0W for the L compartment only.

**Comment by ElectricRCAircraftGuy** [comment]
12:12pm

```
YoLink: 3.9, 54.1, 112.5 
Display: 7, off
Setpoints: 0, off
```

I opened the compartments. The L cooler was rock solid frozen. The R compartment had the two ice bottles about 50% melted with large ice chunks floating in the water inside.

**Comment by ElectricRCAircraftGuy** [comment]
9:13pm

```
YoLink: 2.8, 52.7, 85.1
Display: 1, off
Setpoints: 0, off
```

L is frozen solid. R: both water bottles are still ice cold but nearly 100% melted. There is a tiny 0.5x0.5" piece of floating ice in each water bottle.

See my many photos/screenshots of plots just now.


# Test 6: 7F, 34F again, in Tesla parked outside 

9:22pm setting new Setpoints to 7F, 34F.

Fridge/freezer power draw is 56W.

**Comment by ElectricRCAircraftGuy** [comment]
6:08am

Opened each compartment to look. L bottles are frozen solid. R water bottles are pure liquid. Some frost near top of R compartment. Some water (couple teaspoons?) in bottom.

**Comment by ElectricRCAircraftGuy** [comment]
# Test 7: 7F, 34F again, in Tesla parked in garage

12 Sept 2024

7:57pm

```
YoLink: 9.5, 35.6, 88.7 in car
Display: 11, 36
Setpoints: still 7, 34
```

I just moved the car into the garage and opened the compartments briefly to look inside and dry out the inside of the R compartment with paper towels.

**Comment by ElectricRCAircraftGuy** [comment]
3:53pm

```
YoLink: 7.0, 36.3, 91.0
Display: 8, 36
Setpoints: 7, 34
```

Unplugged freezer. Took it out of my Tesla in the garage. Opened it and checked on it. Closed it. Left it UNPLUGGED in my garage. 

L side was frozen solid. R side had frost on the top rim.


# Test: letting the freezer and fridge naturally cool now.

**Comment by ElectricRCAircraftGuy** [comment]
7:16am

Freezer is unplugged still in my garage. I don't have a data logging thermometer in my garage right now. Just the one in the back of my car in the garage, and a regular thermometer in the garage.

Garage temp: 87F.

```
YoLink: 45.0, 70.3
Display: off, off 
Setpoints: off, off
```

Opening compartments.

L water bottles are about 80% ice still. Solid ice in the center. Water around them. See photos.
R water bottles feel barely cool at all when I drink them. Maybe a tiny bit colder than room temp. Probably about 70F.

**Comment by ElectricRCAircraftGuy** [comment]
8:55pm

```
YoLink: 47.5, 76.1 

Still all off
```

87F in garage on non-YoLink thermometer.

L compartment: skinny bottle is about 1/6 ice. Mostly water. Large 2 quart bottle is about 2/3 ice, mostly ice.

R side: water bottles feel room temp. Ever so slightly cool to the touch. They feel about 76F.

**Comment by ElectricRCAircraftGuy** [comment]
6:48am

```
YoLink: 50.2, 76.8

Still all off
```

87F in garage on non YoLink thermometer.

L compartment: skinny bottle is all water. Large 2 quart bottle is 3/4 water, 1/4 ice.

R compartment: feels room temp. There is heavy condensation on the outside of one of the bottles though, indicating it was cooler than the wet, humid air around it.

**Comment by ElectricRCAircraftGuy** [comment]
16 Sept 2024
7:20am

```
YoLink: 68.9, 79.0

Still all off
```

85F in the garage

L: ice is all melted. Water is barely cool.
R: water is room temp. 

I'll end this experiment today sometime.

Ice lasted a little under 48 hours in the left (\~45 hrs). See screenshots from YoLink app.

**Comment by ElectricRCAircraftGuy** [comment]
17 Sep. 2024
8:05am

```
YoLink: 80.6, 82.0
Still all off
```
86F in garage.

Ending the experiment. Opening the compartments and wiping them dry and leaving them open to air out.

The condensated water in both compartments smells a little bit putrid (rotten). Gross. Cleaning with disinfectant.
But the room temperature water *inside* the bottles tastes fine.

Taking final YoLink screenshots.
